spring.application.name=fossrader-de4

# MongoDB配置
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=fossrader

# 服务器配置
server.port=8080
server.servlet.context-path=/

# 日志配置
logging.level.tech.cspioneer=DEBUG
# 开启MongoDB查询日志
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository.query=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

# Jackson配置
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
